"""phone_number to users table

Revision ID: 005fa234aa45
Revises: 24cdd8609a53
Create Date: 2021-11-28 14:48:43.773936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005fa234aa45'
down_revision = '24cdd8609a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
