"""auto-vote

Revision ID: 24cdd8609a53
Revises: cdaebafb53c6
Create Date: 2021-11-28 14:39:21.286385

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "24cdd8609a53"
down_revision = "cdaebafb53c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "post_id"),
    )
    op.alter_column(
        "posts",
        "published",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.create_unique_constraint(None, "users", ["password"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "posts",
        "published",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.drop_table("votes")
    # ### end Alembic commands ###
